---
   - name: Install Apache and Php Service
     apt:
      name:
         -  apache2
         - libapache2-mod-php8.1
         - software-properties-common
         - php
         - libapache2-mod-php
         - php8.1-mysql
         - php8.1-common
         - php8.1-xml
         - php8.1-xmlrpc
         - php8.1-curl
         - php8.1-gd
         - php8.1-imagick
         - php8.1-cli
         - php8.1-dev
         - php8.1-imap
         - php8.1-mbstring
         - php8.1-opcache
         - php8.1-soap
         - php8.1-zip
         - php8.1-intl
         - php8.1-fpm
      update_cache: yes

    #Create a document root 
   - name: Create document root
     file:
      path: /var/www/poormanalfred
      state: directory
      owner: root
      mode: '0755'
      recurse: yes

   #Reload
   - name: Reload Apache
     service:
      name: apache2
      state: started

   #Restart
   - name: Restart Apache
     service:
      name: apache2
      state: restarted