---
# tasks file for ufw

   - name: Allow everything and enable UFW
     ufw:
       state: enabled
       policy: allow

   - name: Set logging
     ufw:
       logging: 'on'

   - name: Allow OpenSSH
     ufw:
       rule: allow
       name: OpenSSH

   - name: Allow tcp 80
     ufw:
       rule: allow
       port: '80'
       proto: tcp

   - name: Allow tcp 443
     ufw:
       rule: allow
       port: '443'
       proto: tcp